Javascript javascript1 week3
saloumeh-67/hyf-homework pull request #9
Opened 2021-07-29 19:05 UTC by saloumeh-67

homework for Javascript 1 Week 3 .

2021-07-31 14:08 UTC, zuhairtaha requested changes
Good job 👍

2021-07-31 14:08 UTC, zuhairtaha commented on javascript/javascript1/week3/WhenWillWeBeThere.js
> +    const minute = Math.floor((timePeriod % 1) * 60);
Why `%1` ?

2021-07-31 14:08 UTC, zuhairtaha commented on javascript/javascript1/week3/itemArrayRemoval.js
> + names.splice(names.indexOf(nameToRemove),1);
Nice 👍

2021-07-31 14:08 UTC, zuhairtaha commented on javascript/javascript1/week3/notes.js
> +        else if ((id === " ") || (id.typeof !== "number"))
`id.typeof` !!?? 
Do you mean `typeof id`

2021-07-31 14:08 UTC, zuhairtaha commented on javascript/javascript1/week3/notes.js
> +firstNote = getNote(1);
Declare the variable before using it

2021-07-31 14:08 UTC, zuhairtaha commented on javascript/javascript1/week3/series.js
> +        timeWastedInPercentage = (currentDuration / averageLife) * 100;
Declare this variable first. Add `const` / `let`

2021-09-01 11:55 UTC, saloumeh-67 commented on javascript/javascript1/week3/WhenWillWeBeThere.js
> +    const minute = Math.floor((timePeriod % 1) * 60);
conversion of time scale to decimal

2021-09-01 12:05 UTC, merged